name: typeset
description: WhatsApp like text formatting for you!
version: 0.1.0+15
repository: https://github.com/rohanjsh/typeset/

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

 


